### ISSUE TITLE
Problem of compile

### ISSUE THREAD

**Issue by Droppix** [BlockchainCommons/BCLibwallySwift#4]
Hi,

I try to build LibWallySwift framework, but I have an error, if you have any suggestion... Thks

./build.sh
=== Getting Dependencies ===
=== Building C Libraries ===
== wallycore arm64-apple-ios ==
** Build error. **
Log tail:
  CCLD     libsecp256k1.la
./libtool: line 151: -o: command not found
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
make[3]: *** [libsecp256k1.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
** Build error. **

**Comment by wolfmcnally** [comment]
Hi! Please see the deprecation notice for this repo in the README. You're welcome to diagnose and submit a PR that fixes the issue for you, but we are no longer actively maintaining this repo.
